[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info

[program:fastapi]
command=uvicorn api:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/fastapi.log
stderr_logfile=/app/logs/fastapi_err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
environment=DOTENV_PATH="/app/.env"

[program:webdav]
command=python webdav_server.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/webdav.log
stderr_logfile=/app/logs/webdav_err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
